### PR TITLE
Liam's formatting and slight rewrite

### PR DESCRIPTION
**Pull request by Bakerbakura**

### CODE REVIEW

**Comment by dlnnlsn** [comment]
I'll approve your merge request but I don't like being coerced into using your auto-formatter 😛

**Comment by dlnnlsn** [comment]
Out of curiosity, what is the effect of the ```\deflen``` command/what effect does using ```\newlength``` have instead of using ```\def```?

**Comment by Bakerbakura** [comment]
According to someone on StackExchange,

> `\newlength` is a LaTeX macro which defines a new length register, which holds a length as number and can be used for calculations (e.g. using `\addtolength`). The \def macro is the primitive version of `\(re)newcommand` and simply defines the content as string.

I don't quite remember why I made this change; it may have been due to issues with calculations? Anyway, having variables which are lengths actually handled as lengths seems more... _right_ to me.

**Comment by Bakerbakura** [comment]
Thanks for accepting the pull request btw!

**Comment by Bakerbakura** [comment]
> I'll approve your merge request but I don't like being coerced into using your auto-formatter 😛

Wait. What auto-formatter are you talking about? As far as I know there aren't any for LaTeX...

**Pull request merged**
